### ISSUE TITLE
Hiding the progressbar

### ISSUE THREAD

**Issue by tomdevdev** [lsjwzh/MaterialLoadingProgressBar#1]
Hi

Nice library!
I'm having trouble making it go away :)

```
        progressBar.getVisibility(); //value is 0, it's visible
        progressBar.setVisibility(View.GONE);
        progressBar.getVisibility(); //value is 8, still visible!
```

I'm loading my stuff in an asynctask, and in onProgressUpdate, I want to make the progress indicator go away. But it's still visible.

**Comment by lsjwzh** [comment]
thanks for your issue. I have resolved this problem at version 0.4.
And you can also resolve this problem by wrap an layout on progressBar before version 0.4
