### ISSUE TITLE
Rotation animation not shown in Fragment

### ISSUE THREAD

**Issue by rahil2952** [lsjwzh/MaterialLoadingProgressBar#11]
When I used this example inside fragment it is not showing up rotation animation instead it will display only white background circle.

**Comment by michaelgobbers** [comment]
I don't know why this was closed but I can also confirm this issue.
I included this in an listitem in a recyclerview inside a fragment:

code:

```
<com.lsjwzh.widget.materialloadingprogressbar.CircleProgressBar
            local:mlpb_show_arrow="false"
            local:mlpb_enable_circle_background="false"
            local:mlpb_progress_stoke_width="5dp"
            local:mlpb_progress_color="@color/primary"
            local:mlpb_progress_text_visibility="invisible"
            android:layout_gravity="center"
            android:layout_width="50dp"
            android:layout_height="50dp"/>
```

If I set the background enabled then I can confirm that I can only see the background circle.
