### ISSUE TITLE
animation control from action events

### ISSUE THREAD

**Issue by jjhesk** [lsjwzh/MaterialLoadingProgressBar#3]
is that possible to add an animation for the start and the end of the loading event. Like the transition from nothing to scaled back to the original size?

**Comment by lsjwzh** [comment]
Good idea!!!

**Comment by jjhesk** [comment]
I'm glad you like that. 
one method is called. animateShow(boolean n) and another one is animateHide()@

**Comment by zaihuishou** [comment]
Error:(25, 0) Could not read script '/home/zhiqiang/Desktop/MaterialLoadingProgressBar-master/gradle-mvn-push.gradle' as it does not exist.

Why is this?

**Comment by sphairo** [comment]
this component It has the attribute of indeterminate on xml ??? the animation stops :(

**Comment by lsjwzh** [comment]
@zaihuishou  you should add "//" before  "apply from: "${rootDir}/gradle-mvn-push.gradle""

**Comment by amatkivskiy** [comment]
@jjhesk You can easily implement this  performing animation on **CircleProgressBar**.
For example :

```
 ScaleAnimation animation = new ScaleAnimation(0, 1, 0, 1, Animation.RELATIVE_TO_SELF, (float)0.5, Animation.RELATIVE_TO_SELF, (float)0.5);
        animation.setDuration(500);
        animation.setAnimationListener(new Animation.AnimationListener() {
            @Override
            public void onAnimationStart(Animation animation) {

            }

            @Override
            public void onAnimationEnd(Animation animation) {
                progress1.setVisibility(View.VISIBLE);
            }

            @Override
            public void onAnimationRepeat(Animation animation) {

            }
        });
        animation.setFillAfter(true);

      this.progress1.startAnimation(animation);
```
